[package]
name = "core-infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
core-domain = { path = "../core-domain" }
core-application = { path = "../core-application" }
tokio = { workspace = true }
surrealdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }