use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuditableAction {
    Login,
    Logout,
    SwitchCompany,
    CreateCompany,
    UpdateCompany,
    DeleteCompany,
    CreateUser,
    UpdateUser,
    DeleteUser,
    DisableUser,
    UnlockUser,
    CreateRole,
    UpdateRole,
    DeleteRole,
    AddUserProfile,
    UpdateUserProfile,
    RemoveUserProfile,
    CreateContact,
    UpdateContact,
    DeleteContact,
    UpdatePerson,
    DeactivateCertificate,
    SaveSettings,
    CreatePermissionPolicy,
    DeletePermissionPolicy,
    CreateDocument,
    UpdateDocument,
    DeleteDocument,
    PostDocument,
    CancelDocument,
    ArchiveDocument,
    CreateCatalogEntry,
    UpdateCatalogEntry,
    DeleteCatalogEntry,
    EmitEvent,
    ReplayEvent,
    ExecuteScript,
}

impl AuditableAction {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Login => "login",
            Self::Logout => "logout",
            Self::SwitchCompany => "switch_company",
            Self::CreateCompany => "create_company",
            Self::UpdateCompany => "update_company",
            Self::DeleteCompany => "delete_company",
            Self::CreateUser => "create_user",
            Self::UpdateUser => "update_user",
            Self::DeleteUser => "delete_user",
            Self::DisableUser => "disable_user",
            Self::UnlockUser => "unlock_user",
            Self::CreateRole => "create_role",
            Self::UpdateRole => "update_role",
            Self::DeleteRole => "delete_role",
            Self::AddUserProfile => "add_user_profile",
            Self::UpdateUserProfile => "update_user_profile",
            Self::RemoveUserProfile => "remove_user_profile",
            Self::CreateContact => "create_contact",
            Self::UpdateContact => "update_contact",
            Self::DeleteContact => "delete_contact",
            Self::UpdatePerson => "update_person",
            Self::DeactivateCertificate => "deactivate_certificate",
            Self::SaveSettings => "save_settings",
            Self::CreatePermissionPolicy => "create_permission_policy",
            Self::DeletePermissionPolicy => "delete_permission_policy",
            Self::CreateDocument => "create_document",
            Self::UpdateDocument => "update_document",
            Self::DeleteDocument => "delete_document",
            Self::PostDocument => "post_document",
            Self::CancelDocument => "cancel_document",
            Self::ArchiveDocument => "archive_document",
            Self::CreateCatalogEntry => "create_catalog_entry",
            Self::UpdateCatalogEntry => "update_catalog_entry",
            Self::DeleteCatalogEntry => "delete_catalog_entry",
            Self::EmitEvent => "emit_event",
            Self::ReplayEvent => "replay_event",
            Self::ExecuteScript => "execute_script",
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::Login => "Вход в систему",
            Self::Logout => "Выход из системы",
            Self::SwitchCompany => "Смена компании",
            Self::CreateCompany => "Создание компании",
            Self::UpdateCompany => "Обновление компании",
            Self::DeleteCompany => "Удаление компании",
            Self::CreateUser => "Создание пользователя",
            Self::UpdateUser => "Обновление пользователя",
            Self::DeleteUser => "Удаление пользователя",
            Self::DisableUser => "Блокировка пользователя",
            Self::UnlockUser => "Разблокировка пользователя",
            Self::CreateRole => "Создание роли",
            Self::UpdateRole => "Обновление роли",
            Self::DeleteRole => "Удаление роли",
            Self::AddUserProfile => "Добавление рабочего профиля",
            Self::UpdateUserProfile => "Обновление рабочего профиля",
            Self::RemoveUserProfile => "Удаление рабочего профиля",
            Self::CreateContact => "Создание контакта",
            Self::UpdateContact => "Обновление контакта",
            Self::DeleteContact => "Удаление контакта",
            Self::UpdatePerson => "Обновление персоны",
            Self::DeactivateCertificate => "Деактивация сертификата",
            Self::SaveSettings => "Сохранение настроек",
            Self::CreatePermissionPolicy => "Создание политики доступа",
            Self::DeletePermissionPolicy => "Удаление политики доступа",
            Self::CreateDocument => "Создание документа",
            Self::UpdateDocument => "Обновление документа",
            Self::DeleteDocument => "Удаление документа",
            Self::PostDocument => "Проведение документа",
            Self::CancelDocument => "Отмена документа",
            Self::ArchiveDocument => "Архивация документа",
            Self::CreateCatalogEntry => "Создание записи справочника",
            Self::UpdateCatalogEntry => "Обновление записи справочника",
            Self::DeleteCatalogEntry => "Удаление записи справочника",
            Self::EmitEvent => "Эмиссия события",
            Self::ReplayEvent => "Повторная обработка события",
            Self::ExecuteScript => "Выполнение скрипта",
        }
    }

    pub fn icon(&self) -> &'static str {
        match self {
            Self::Login => "fa-solid fa-right-to-bracket text-success-500",
            Self::Logout => "fa-solid fa-right-from-bracket text-surface-500",
            Self::SwitchCompany => "fa-solid fa-right-left text-warn-500",
            Self::CreateCompany => "fa-solid fa-building text-primary-500",
            Self::UpdateCompany => "fa-solid fa-building text-primary-500",
            Self::DeleteCompany => "fa-solid fa-building text-error-500",
            Self::CreateUser => "fa-solid fa-user-plus text-primary-500",
            Self::UpdateUser => "fa-solid fa-user-pen text-primary-500",
            Self::DeleteUser => "fa-solid fa-user-minus text-error-500",
            Self::DisableUser => "fa-solid fa-user-lock text-warn-500",
            Self::UnlockUser => "fa-solid fa-user-check text-success-500",
            Self::CreateRole => "fa-solid fa-shield-halved text-primary-500",
            Self::UpdateRole => "fa-solid fa-shield-halved text-primary-500",
            Self::DeleteRole => "fa-solid fa-shield-halved text-error-500",
            Self::AddUserProfile => "fa-solid fa-id-badge text-primary-500",
            Self::UpdateUserProfile => "fa-solid fa-id-badge text-primary-500",
            Self::RemoveUserProfile => "fa-solid fa-id-badge text-error-500",
            Self::CreateContact => "fa-solid fa-address-card text-primary-500",
            Self::UpdateContact => "fa-solid fa-address-card text-primary-500",
            Self::DeleteContact => "fa-solid fa-address-card text-error-500",
            Self::UpdatePerson => "fa-solid fa-user-pen text-primary-500",
            Self::DeactivateCertificate => "fa-solid fa-certificate text-warn-500",
            Self::SaveSettings => "fa-solid fa-gear text-primary-500",
            Self::CreatePermissionPolicy => "fa-solid fa-key text-primary-500",
            Self::DeletePermissionPolicy => "fa-solid fa-key text-error-500",
            Self::CreateDocument => "fa-solid fa-file-circle-plus text-primary-500",
            Self::UpdateDocument => "fa-solid fa-file-pen text-primary-500",
            Self::DeleteDocument => "fa-solid fa-file-circle-xmark text-error-500",
            Self::PostDocument => "fa-solid fa-file-circle-check text-success-500",
            Self::CancelDocument => "fa-solid fa-file-circle-minus text-warn-500",
            Self::ArchiveDocument => "fa-solid fa-box-archive text-surface-500",
            Self::CreateCatalogEntry => "fa-solid fa-book text-primary-500",
            Self::UpdateCatalogEntry => "fa-solid fa-book text-primary-500",
            Self::DeleteCatalogEntry => "fa-solid fa-book text-error-500",
            Self::EmitEvent => "fa-solid fa-bolt text-warn-500",
            Self::ReplayEvent => "fa-solid fa-rotate text-primary-500",
            Self::ExecuteScript => "fa-solid fa-code text-primary-500",
        }
    }

    pub fn target_type(&self) -> &'static str {
        match self {
            Self::Login | Self::Logout => "session",
            Self::SwitchCompany => "company",
            Self::CreateCompany | Self::UpdateCompany | Self::DeleteCompany => "company",
            Self::CreateUser | Self::UpdateUser | Self::DeleteUser
            | Self::DisableUser | Self::UnlockUser => "user",
            Self::CreateRole | Self::UpdateRole | Self::DeleteRole => "role",
            Self::AddUserProfile | Self::UpdateUserProfile | Self::RemoveUserProfile => "user_profile",
            Self::CreateContact | Self::UpdateContact | Self::DeleteContact => "user_contact",
            Self::UpdatePerson => "person",
            Self::DeactivateCertificate => "user_certificate",
            Self::SaveSettings => "setting",
            Self::CreatePermissionPolicy | Self::DeletePermissionPolicy => "permission_policy",
            Self::CreateDocument | Self::UpdateDocument | Self::DeleteDocument
            | Self::PostDocument | Self::CancelDocument | Self::ArchiveDocument => "document",
            Self::CreateCatalogEntry | Self::UpdateCatalogEntry
            | Self::DeleteCatalogEntry => "catalog_entry",
            Self::EmitEvent | Self::ReplayEvent => "event",
            Self::ExecuteScript => "rhai_script",
        }
    }
}

impl std::fmt::Display for AuditableAction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for AuditableAction {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "login" => Ok(Self::Login),
            "logout" => Ok(Self::Logout),
            "switch_company" => Ok(Self::SwitchCompany),
            "create_company" => Ok(Self::CreateCompany),
            "update_company" => Ok(Self::UpdateCompany),
            "delete_company" => Ok(Self::DeleteCompany),
            "create_user" => Ok(Self::CreateUser),
            "update_user" => Ok(Self::UpdateUser),
            "delete_user" => Ok(Self::DeleteUser),
            "disable_user" => Ok(Self::DisableUser),
            "unlock_user" => Ok(Self::UnlockUser),
            "create_role" => Ok(Self::CreateRole),
            "update_role" => Ok(Self::UpdateRole),
            "delete_role" => Ok(Self::DeleteRole),
            "add_user_profile" => Ok(Self::AddUserProfile),
            "update_user_profile" => Ok(Self::UpdateUserProfile),
            "remove_user_profile" => Ok(Self::RemoveUserProfile),
            "create_contact" => Ok(Self::CreateContact),
            "update_contact" => Ok(Self::UpdateContact),
            "delete_contact" => Ok(Self::DeleteContact),
            "update_person" => Ok(Self::UpdatePerson),
            "deactivate_certificate" => Ok(Self::DeactivateCertificate),
            "save_settings" => Ok(Self::SaveSettings),
            "create_permission_policy" => Ok(Self::CreatePermissionPolicy),
            "delete_permission_policy" => Ok(Self::DeletePermissionPolicy),
            "create_document" => Ok(Self::CreateDocument),
            "update_document" => Ok(Self::UpdateDocument),
            "delete_document" => Ok(Self::DeleteDocument),
            "post_document" => Ok(Self::PostDocument),
            "cancel_document" => Ok(Self::CancelDocument),
            "archive_document" => Ok(Self::ArchiveDocument),
            "create_catalog_entry" => Ok(Self::CreateCatalogEntry),
            "update_catalog_entry" => Ok(Self::UpdateCatalogEntry),
            "delete_catalog_entry" => Ok(Self::DeleteCatalogEntry),
            "emit_event" => Ok(Self::EmitEvent),
            "replay_event" => Ok(Self::ReplayEvent),
            "execute_script" => Ok(Self::ExecuteScript),
            _ => Err(format!("Unknown audit action: {s}")),
        }
    }
}
